export { default as MainHeader } from './MainHeader'
export { default as Footer } from './Footer'
export { default as Live } from './Live'
export { default as Categories } from './Categories'
export { default as News } from './News'