import Head from 'next/head'
import Image from 'next/image'
import React, { useState } from 'react'

import { FaFacebookF } from 'react-icons/fa'
import { BsTwitter, BsYoutube, BsInstagram } from 'react-icons/bs'
import { FiChevronDown } from 'react-icons/fi'

export default function Home() {
  const [isClicked, setIsClicked] = useState('live-sports')
  const [open, setOpen] = useState(0)

  const handleOpen = (value) => {
    setOpen(open === value ? 0 : value)
  }

  const news_content = [
    {
      id: "live-sports",
      heading: "Live Sports",
      description: "Catch your games at home or on the go. Stream live games from major college and pro leagues including the NCAA®, NBA, NHL, NFL, and more.",
      channels: [
        { image: "/img/live-sports-logo-1.png" },
        { image: "/img/live-sports-logo-2.png" },
        { image: "/img/live-sports-logo-3.svg" },
        { image: "/img/live-sports-logo-4.png" },
      ]
    },
    {
      id: "breaking-news",
      heading: "Breaking News",
      description: "Keep pace with what's going on locally and globally with trusted opinions from all the top news networks.",
      channels: [
        { image: "/img/breaking-news-logo-1.png" },
        { image: "/img/breaking-news-logo-2.svg" },
        { image: "/img/breaking-news-logo-3.png" },
        { image: "/img/breaking-news-logo-4.svg" },
      ]
    },
    {
      id: "biggest-events",
      heading: "Biggest Events",
      description: "Spectacular, can't-miss moments like the Olympics, Grammys®, Oscars®, Emmys®, and more.",
      channels: [
        { image: "/img/biggest-events-logo-1.png" },
        { image: "/img/biggest-events-logo-2.png" },
        { image: "/img/biggest-events-logo-3.png" },
        { image: "/img/biggest-events-logo-4.png" },
      ]
    }
  ]

  return (
    <div>
      <Head>
        <title>Stream TV and Movies Live and Online | Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <header className='header'>
          <nav className='header__nav'>
            <img src="/img/logo.png" alt="" className="logo" />
            <ul>
              <li><button className="login">log in</button></li>
            </ul>
          </nav>

          <div className="header__content">
            <h4>Bundle with any hulu plan & save</h4>
            <img src="/img/logos.png" alt="logos" className="banner" />
            <div className="header__text--description">Get endless entertainment, live sports, and the shows and movies you love.</div>
            <button className="cta">get the disney bundle</button>
            <div className="legal__text">
              <a className='underline' href="#">What&apos;s included?</a>
              <span className='font-light'> See</span>
              <a className='underline' href="#"> Bundle terms</a>
            </div>
            <div className="helper__text">Sign up for Hulu only</div>
          </div>
        </header>

        <section className="section categories">
          <div className="categories__content">
            <h4>included in all plans</h4>
            <div className="text--heading">All The TV You Love</div>
            <div className="text--description">Stream full seasons of exclusive series, current-season episodes, hit movies, Hulu Originals, kids shows, and more.</div>
          </div>

          <div className="categories__grid covers">
            <div className="cover--1">
              <Image src='/img/cover-1.jpg' height={500} width={300} />
              <div className="cover__overlay"></div>
              <div className="cover__text">
                <div className="cover__subheading">Past & Current Seasons</div>
                <div className="cover__heading">TV Shows</div>
              </div>
            </div>

            <div className="cover--2">
              <Image src='/img/cover-2.jpg' height={500} width={300} />
              <div className="cover__overlay"></div>
              <div className="cover__text">
                <div className="cover__subheading">New & Classic</div>
                <div className="cover__heading">Movies</div>
              </div>
            </div>

            <div className="cover--3">
              <Image src='/img/cover-3.jpg' height={500} width={300} />
              <div className="cover__overlay"></div>
              <div className="cover__text">
                <div className="cover__subheading">Groundbreaking</div>
                <div className="cover__heading">Hulu Originals</div>
              </div>
            </div>

            <div className="cover--4">
              <Image src='/img/cover-4.jpg' height={500} width={300} />
              <div className="cover__overlay"></div>
              <div className="cover__text">
                <div className="cover__subheading">Add-on</div>
                <div className="cover__heading">Premiums</div>
              </div>
            </div>
          </div>
          <div className="legal__text">Premium network add-ons available for an additional cost</div>
        </section>

        <section className="section live">
          <h4>Hulu + Live TV, now with disney+ and espn+</h4>

          <div className="text--heading">Live TV Makes It Better</div>

          <div className="text--description">Make the switch from cable. Get 75+ top channels on Hulu + Live TV with your favorite live sports, news, and events - plus the entire Hulu streaming library. With Unlimited DVR, store Live TV recordings for up to nine months and fast-forward through your DVR content. Access endless entertainment with Disney+ and live sports with ESPN+.</div>

          <div className="helper__text uppercase">view channels in your area</div>

          <div className="chevron"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6 animate-bounce">
            <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
          </svg>
          </div>
        </section>

        <section className={`news ${ isClicked }`} >
          <div className="news__content">
            <div className="tabs">
              <ul className="flex flex-wrap gap-2 -mb-px">
                <li className="mr-2"><button onClick={() => setIsClicked('live-sports')} className={`tab__links ${ isClicked === 'live-sports' && 'active' }`}>Live Sports</button></li>
                <li className="mr-2"><button onClick={() => setIsClicked('breaking-news')} className={`tab__links ${ isClicked === 'breaking-news' && 'active' }`} aria-current="page">Breaking News</button></li>
                <li className="mr-2"><button onClick={() => setIsClicked('biggest-events')} className={`tab__links ${ isClicked === 'biggest-events' && 'active' }`}>Biggest Events</button></li>
              </ul>
            </div>
            {news_content.map((content, i) => (
              <div key={i} id={content.id} className={`${ isClicked === content.id ? 'block' : 'hidden' } space-y-4`}>
                <div className="text--heading mt-10">{content.heading}</div>
                <div className="text--description">{content.description}</div>
                <div className="channels">
                  {content.channels.map((channel, i) => (
                    <div key={i} className="channel">
                      <img src={channel.image} alt="" />
                    </div>
                  ))}
                </div>
                <div className="legal__text max-w-xs mx-auto md:max-w-md">Live TV plan required. Regional restrictions, blackouts and additional terms apply. <span className='underline'>See details</span></div>
              </div>
            ))}
          </div>
        </section>
      </main>

      <footer className="footer">
        <div className="footer--wrapper">
          <div className="footer--links">
            <div>
              <button className='accordion' onClick={() => handleOpen(1)}>Browse <FiChevronDown /></button>
              <ul className={`panel__list browse ${open === 1 ? 'block' : ''}`}>
                <span>
                  <li>Streaming Library</li>
                  <li>Live TV</li>
                  <li>Live News</li>
                  <li>Live Sports</li>
                </span>
                <span>
                  <li>TV Shows</li>
                  <li>Movies</li>
                  <li>Originals</li>
                  <li>Networks</li>
                  <li>Kids</li>
                  <li>FX</li>
                </span>
                <span>
                  <li>HBO Max™</li>
                  <li>Cinemax</li>
                  <li>Showtime</li>
                  <li>STARZ</li>
                </span>
                <span>
                  <li>Hulu, Disney+, and ESPN+</li>
                  <li>Hulu (No Ads), Disney+, and ESPN+</li>
                  <li>Student Discount</li>
                </span>
              </ul>
            </div>
            <div>
              <button className='accordion' onClick={() => handleOpen(2)}>Help <FiChevronDown /></button>
              <ul className={`panel__list ${open === 2 ? 'block' : ''}`}>
                <li>Account & Billing</li>
                <li>Plans & Pricing</li>
                <li>Supported Devices</li>
                <li>Accessibility</li>
              </ul>
            </div>
            <div>
              <button className='accordion' onClick={() => handleOpen(3)}>About Us <FiChevronDown /></button>
              <ul className={`panel__list ${open === 3 ? 'block' : ''}`}>
                <li>Shop Hulu</li>
                <li>Press</li>
                <li>Jobs</li>
                <li>Contact</li>
              </ul>
            </div>
          </div>
          <div className="footer--social">
            <FaFacebookF />
            <BsTwitter />
            <BsYoutube />
            <BsInstagram />
          </div>
          <div className="footer--legal">
            <span>© 2022 Hulu, LLC</span>
            <span>About Ads</span>
            <span>Terms of Use</span>
            <span>Privacy Policy</span>
            <span>Do Not Sell My Personal Information</span>
            <span>Your California Privacy Rights</span>
            <span>TV Parental Guidelines</span>
            <span>Sitemap</span>
          </div>
        </div>
      </footer>
    </div>
  )
}