import Head from 'next/head'
import React from 'react'

function home() {
  return (
    <div>
      <Head>
        <title>Stream TV and Movies Live and Online | Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <header className='header'>
          <nav className='header__nav'>
            <img src="/img/logo.png" alt="" className="logo" />
            <ul>
              <li><button className="login">log in</button></li>
            </ul>
          </nav>

          <div className="header__content">
            <h4>Bundle with any hulu plan & save</h4>
            <img src="/img/logos.png" alt="logos" className="banner" />
            <div className="header__text--description">Get endless entertainment, live sports, and the shows and movies you love.</div>
            <button className="cta">get the disney bundle</button>
            <div className="legal__text">
              <a className='underline' href="#">What's included?</a>
              <span className='font-light'> See</span>
              <a className='underline' href="#"> Bundle terms</a>
            </div>
            <div className="helper__text">Sign up for Hulu only</div>
          </div>
        </header>

        <section className="categories">
          <h4>included in all plans</h4>
          <div className="main__heading">All The TV You Love</div>
          <div className="main__text">Stream full seasons of exclusive series, current-season episodes, hit movies, Hulu Originals, kids shows, and more.</div>
          <div className="categories__grid">
            <div className="cover--1">
              <div className="categories__subheading">Past & Current Seasons</div>
              <div className="categories__heading">TV Shows</div>
            </div>
            <div className="cover--2"></div>
            <div className="categories__subheading">New & Classic</div>
              <div className="categories__heading">Movies</div>
            <div className="cover--3">
            <div className="categories__subheading">Groundbreaking</div>
              <div className="categories__heading">Hulu Originals</div>
            </div>
            <div className="cover--4">
            <div className="categories__subheading">Add-on</div>
              <div className="categories__heading">Premiums</div>
            </div>
          </div>
          <div className="legal__text">Premium network add-ons available for an additional cost</div>
        </section>

        <section className="live">
          <h4>Hulu + Live TV, now with disney+ and espn+</h4>
          <div className="main__heading">Live TV Makes It Better</div>
          <div className="main__text">Make the switch from cable. Get 75+ top channels on Hulu + Live TV with your favorite live sports, news, and events - plus the entire Hulu streaming library. With Unlimited DVR, store Live TV recordings for up to nine months and fast-forward through your DVR content. Access endless entertainment with Disney+ and live sports with ESPN+.</div>
          <div className="helper__text">view channels in your area</div>
          <div className="chevron">arrowDown</div>
        </section>

        <section className="news">
          <div className="news__content">
            <div className="main__heading">Live Sports</div>
            <div className="main__text">Catch your games at home or on the go. Stream live games from major college and pro leagues including the NCAA®, NBA, NHL, NFL, and more.</div>
            <div className="channels"></div>
            <div className="legal__text">Live TV plan required. Regional restrictions, blackouts and additional terms apply. See details</div>
          </div>
        </section>
      </main>
    </div>
  )
}

export default home