import Head from 'next/head'

import React from 'react'

import { MainHeader, Categories, Live, News, Footer } from '../components'

export default function Home() {

  return (
    <div>
      <Head>
        <title>Stream TV and Movies Live and Online | Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <MainHeader />
        <Categories />
        <Live />
        <News />
      </main>

      <Footer />
    </div>
  )
}